mysqldata:
  image: jaarandaz/mariadb-data

mysql:
  image: mariadb
  environment:
    MYSQL_PASS: root
  volumes_from:
    - mysqldata

phpnginx:
  image: jaarandaz/php-fpm-nginx
  links:
    - mysql
  ports:
    - "80:80"
  volumes:
    - ./nginx:/etc/nginx/sites-available
    - ./:/var/www
